# Generated by Django 2.1.4 on 2020-03-03 12:23

import DiceUp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiceUpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_picture', models.ImageField(upload_to='DiceUp/', validators=[DiceUp.models.validate_image])),
                ('dice_picture', models.ImageField(default=None, upload_to='')),
                ('instruction', models.FileField(default=None, upload_to='')),
            ],
        ),
    ]
